name: Publish Package Nuget PackageNugetTemplating

on:
  release:
    types: [published]

jobs:
   push_to_registry:
       name: Push package nuget PackageNugetTemplating to registry
       runs-on: ubuntu-latest
       steps:
         - name: Check out the repo
           uses: actions/checkout@v4
